# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos67"

  # omnibus
  config.omnibus.chef_version = :latest

  # chef
  config.vm.provision "chef_solo" do |chef|
    chef.cookbooks_path = ["./cookbooks", "./site-cookbooks"]
    chef.add_recipe "rbenv"
    chef.add_recipe "rbenv::ruby_build"
    chef.add_recipe "ruby-install"
  end
end
